### ISSUE TITLE
ValueError: Image features and image tokens do not match: tokens: 1991, features 2990

### ISSUE THREAD

**Issue by zhangboshen** [QwenLM/Qwen3-VL#556]
Related discussion : https://github.com/huggingface/transformers/issues/34625
I met this problem when sft qwen2-vl-7b using lora, training data is multi-images QA.

**Comment by CloudComputing-linux** [comment]
same problem

**Comment by thusinh1969** [comment]
What happened ? I used to be able to finetune Qwen2-VL with multiple images just fine. What is the bug now ?!?!

Cheers,
Steve

**Comment by gouqi666** [comment]
@zhangboshen @thusinh1969 @CloudComputing-linux @hzhwcmhf @c0g  anyone have solution for this mismatch problem? i use llamafactory to train qwen2-vl

**Comment by mrwwk** [comment]
same

**Comment by zhangboshen** [comment]
@thusinh1969 @gouqi666 @CloudComputing-linux @mrwwk 
I'm able to train the model by setting cutoff_len to a larger num that default. e.g., 10000;
It seems like this parameter affect the image token-image feature alignment to some extent.

**Comment by koleshjr** [comment]
Same I am facing this issue. Any fixes?

**Comment by LeeOrange-is-me** [comment]
`transformers-4.50.0.dev0` may solve this problem, but ...

**Comment by YangEgp** [comment]
<img width="1492" alt="Image" src="https://github.com/user-attachments/assets/23e2ec13-2369-4ca2-b600-170394555971" />
有没有大佬知道怎么办的

**Comment by LeeOrange-is-me** [comment]
你要不要试一下transformers-4.50.0.dev0

**Comment by LeeOrange-is-me** [comment]
😭 我解决了 为什么Qwen2-vl-7B出错了。
废话不多说，先看我的代码
Code run faster than my word: 
```python 
model_name = '/path/to/Qwen2-VL-7B' 
processor = AutoProcessor.from_pretrained(model_name,trust_remote_code=True)
model = Qwen2VLForConditionalGeneration.from_pretrained(model_name, device_map="auto", trust_remote_code=True)

messages = [
    {
        "role": "user",
        "content":[ 
        {
        "type":"text" ,"text":"TELL ME WHY!!!!"
        }
    ]
    }
]

text_input = processor.apply_chat_template(messages, tokenize=False, add_generation_prompt=True)
# About the text_input, it is ""!  This is the key point, you can print(text_input)
image_inputs, video_inputs = process_vision_info(messages)
inputs = processor(
            text=[text_input],
            images=image_inputs,
            videos=video_inputs,
            padding=True,
            return_tensors="pt")
inputs = inputs.to("cuda:0")
output_ids =model.generate(**inputs, max_new_tokens=256)
generated_ids_trimmed = [output_ids[len(input_ids):] for input_ids, output_ids in zip(inputs.input_ids, output_ids )]
response= processor.batch_decode(generated_ids_trimmed, skip_special_tokens=True, clean_up_tokenization_spaces=True)
``` 
it returns :
```APL
Traceback (most recent call last):
  File "/data/lsd/work/LLM/JailBreakV_28K/attack_models/Qwen.py", line 64, in <module>
    ret = model.inference("/data/lsd/work/LLM/JailBreakV_28K/JailBreakV_28k/query_related/SD_related_0.png", "hi!describe the picture")
  File "/data/lsd/work/LLM/JailBreakV_28K/attack_models/Qwen.py", line 56, in inference
    output_ids =self. model.generate(**inputs, max_new_tokens=256)
  File "/data/lsd/anaconda3/envs/jbv/lib/python3.9/site-packages/torch/utils/_contextlib.py", line 115, in decorate_context
    return func(*args, **kwargs)
  File "/data/lsd/anaconda3/envs/jbv/lib/python3.9/site-packages/transformers/generation/utils.py", line 2465, in generate
    result = self._sample(
  File "/data/lsd/anaconda3/envs/jbv/lib/python3.9/site-packages/transformers/generation/utils.py", line 3424, in _sample
    model_inputs = self.prepare_inputs_for_generation(input_ids, **model_kwargs)
  File "/data/lsd/anaconda3/envs/jbv/lib/python3.9/site-packages/transformers/models/qwen2_vl/modeling_qwen2_vl.py", line 1764, in prepare_inputs_for_generation
    model_inputs = super().prepare_inputs_for_generation(
  File "/data/lsd/anaconda3/envs/jbv/lib/python3.9/site-packages/transformers/generation/utils.py", line 507, in prepare_inputs_for_generation
    inputs_embeds, input_ids = self._cache_dependant_input_preparation(
  File "/data/lsd/anaconda3/envs/jbv/lib/python3.9/site-packages/transformers/generation/utils.py", line 406, in _cache_dependant_input_preparation
    or (cache_position[-1] >= input_ids.shape[1])  # Exception 3.(This may be varified due to your code.)
```
It may be due to the model in `huggingface` being something wrong. ~ If the `chat_template.json` in your model path is:
```
{ 
 "chat_template": "{% if messages is string %}{{ messages }}{% else %}{% for content in messages %}{% if content['type'] == 'image' or 'image' in content or 'image_url' in content %}<|vision_start|><|image_pad|><|vision_end|>{% elif content['type'] == 'video' or 'video' in content %}<|vision_start|><|video_pad|><|vision_end|>{% elif 'text' in content %}{{ content['text'] }}{% endif %}{% endfor %}{% endif %}" 
 } 
```
And you should use `chat_template.json` in `Qwen2.5` or other versions. I copy the belowing:
```
{
    "chat_template": "{% set image_count = namespace(value=0) %}{% set video_count = namespace(value=0) %}{% for message in messages %}{% if loop.first and message['role'] != 'system' %}<|im_start|>system\nYou are a helpful assistant.<|im_end|>\n{% endif %}<|im_start|>{{ message['role'] }}\n{% if message['content'] is string %}{{ message['content'] }}<|im_end|>\n{% else %}{% for content in message['content'] %}{% if content['type'] == 'image' or 'image' in content or 'image_url' in content %}{% set image_count.value = image_count.value + 1 %}{% if add_vision_id %}Picture {{ image_count.value }}: {% endif %}<|vision_start|><|image_pad|><|vision_end|>{% elif content['type'] == 'video' or 'video' in content %}{% set video_count.value = video_count.value + 1 %}{% if add_vision_id %}Video {{ video_count.value }}: {% endif %}<|vision_start|><|video_pad|><|vision_end|>{% elif 'text' in content %}{{ content['text'] }}{% endif %}{% endfor %}<|im_end|>\n{% endif %}{% endfor %}{% if add_generation_prompt %}<|im_start|>assistant\n{% endif %}"
}
``` 
Then you should replace your `chat_template.json` with the bellow one.
And this may help you.

**Comment by miikatoi** [comment]
It seems to happen very randomly to me when training with unsloth.

I managed to work around it by keeping the input size constant (with fixed prompt length and image size). If I randomly resize the images, it always raises the error during training.

**Comment by aJupyter** [comment]
这个问题好像还没解决？

**Comment by munian08** [comment]
遇到这个问题+1

**Comment by Jdemon233** [comment]
> 😭 我解决了 为什么Qwen2-vl-7B出错了。 废话不多说，先看我的代码 Code run faster than my word:
> 
> model_name = '/path/to/Qwen2-VL-7B' 
> processor = AutoProcessor.from_pretrained(model_name,trust_remote_code=True)
> model = Qwen2VLForConditionalGeneration.from_pretrained(model_name, device_map="auto", trust_remote_code=True)
> 
> messages = [
>     {
>         "role": "user",
>         "content":[ 
>         {
>         "type":"text" ,"text":"TELL ME WHY!!!!"
>         }
>     ]
>     }
> ]
> 
> text_input = processor.apply_chat_template(messages, tokenize=False, add_generation_prompt=True)
> # About the text_input, it is ""!  This is the key point, you can print(text_input)
> image_inputs, video_inputs = process_vision_info(messages)
> inputs = processor(
>             text=[text_input],
>             images=image_inputs,
>             videos=video_inputs,
>             padding=True,
>             return_tensors="pt")
> inputs = inputs.to("cuda:0")
> output_ids =model.generate(**inputs, max_new_tokens=256)
> generated_ids_trimmed = [output_ids[len(input_ids):] for input_ids, output_ids in zip(inputs.input_ids, output_ids )]
> response= processor.batch_decode(generated_ids_trimmed, skip_special_tokens=True, clean_up_tokenization_spaces=True)
> it returns :
> 
> Traceback (most recent call last):
>   File "/data/lsd/work/LLM/JailBreakV_28K/attack_models/Qwen.py", line 64, in <module>
>     ret = model.inference("/data/lsd/work/LLM/JailBreakV_28K/JailBreakV_28k/query_related/SD_related_0.png", "hi!describe the picture")
>   File "/data/lsd/work/LLM/JailBreakV_28K/attack_models/Qwen.py", line 56, in inference
>     output_ids =self. model.generate(**inputs, max_new_tokens=256)
>   File "/data/lsd/anaconda3/envs/jbv/lib/python3.9/site-packages/torch/utils/_contextlib.py", line 115, in decorate_context
>     return func(*args, **kwargs)
>   File "/data/lsd/anaconda3/envs/jbv/lib/python3.9/site-packages/transformers/generation/utils.py", line 2465, in generate
>     result = self._sample(
>   File "/data/lsd/anaconda3/envs/jbv/lib/python3.9/site-packages/transformers/generation/utils.py", line 3424, in _sample
>     model_inputs = self.prepare_inputs_for_generation(input_ids, **model_kwargs)
>   File "/data/lsd/anaconda3/envs/jbv/lib/python3.9/site-packages/transformers/models/qwen2_vl/modeling_qwen2_vl.py", line 1764, in prepare_inputs_for_generation
>     model_inputs = super().prepare_inputs_for_generation(
>   File "/data/lsd/anaconda3/envs/jbv/lib/python3.9/site-packages/transformers/generation/utils.py", line 507, in prepare_inputs_for_generation
>     inputs_embeds, input_ids = self._cache_dependant_input_preparation(
>   File "/data/lsd/anaconda3/envs/jbv/lib/python3.9/site-packages/transformers/generation/utils.py", line 406, in _cache_dependant_input_preparation
>     or (cache_position[-1] >= input_ids.shape[1])  # Exception 3.(This may be varified due to your code.)
> It may be due to the model in `huggingface` being something wrong. ~ If the `chat_template.json` in your model path is:
> 
> ```
> { 
>  "chat_template": "{% if messages is string %}{{ messages }}{% else %}{% for content in messages %}{% if content['type'] == 'image' or 'image' in content or 'image_url' in content %}<|vision_start|><|image_pad|><|vision_end|>{% elif content['type'] == 'video' or 'video' in content %}<|vision_start|><|video_pad|><|vision_end|>{% elif 'text' in content %}{{ content['text'] }}{% endif %}{% endfor %}{% endif %}" 
>  } 
> ```
> 
> And you should use `chat_template.json` in `Qwen2.5` or other versions. I copy the belowing:
> 
> ```
> {
>     "chat_template": "{% set image_count = namespace(value=0) %}{% set video_count = namespace(value=0) %}{% for message in messages %}{% if loop.first and message['role'] != 'system' %}<|im_start|>system\nYou are a helpful assistant.<|im_end|>\n{% endif %}<|im_start|>{{ message['role'] }}\n{% if message['content'] is string %}{{ message['content'] }}<|im_end|>\n{% else %}{% for content in message['content'] %}{% if content['type'] == 'image' or 'image' in content or 'image_url' in content %}{% set image_count.value = image_count.value + 1 %}{% if add_vision_id %}Picture {{ image_count.value }}: {% endif %}<|vision_start|><|image_pad|><|vision_end|>{% elif content['type'] == 'video' or 'video' in content %}{% set video_count.value = video_count.value + 1 %}{% if add_vision_id %}Video {{ video_count.value }}: {% endif %}<|vision_start|><|video_pad|><|vision_end|>{% elif 'text' in content %}{{ content['text'] }}{% endif %}{% endfor %}<|im_end|>\n{% endif %}{% endfor %}{% if add_generation_prompt %}<|im_start|>assistant\n{% endif %}"
> }
> ```
> 
> Then you should replace your `chat_template.json` with the bellow one. And this may help you.

你这个和Issue的报错不一样吧，我在llava里也看到你了

**Comment by JlPang863** [comment]
> > 😭 我解决了 为什么Qwen2-vl-7B出错了。 废话不多说，先看我的代码 Code run faster than my word:
> > model_name = '/path/to/Qwen2-VL-7B'
> > processor = AutoProcessor.from_pretrained(model_name,trust_remote_code=True)
> > model = Qwen2VLForConditionalGeneration.from_pretrained(model_name, device_map="auto", trust_remote_code=True)
> > messages = [
> > {
> > "role": "user",
> > "content":[
> > {
> > "type":"text" ,"text":"TELL ME WHY!!!!"
> > }
> > ]
> > }
> > ]
> > text_input = processor.apply_chat_template(messages, tokenize=False, add_generation_prompt=True)
> > # About the text_input, it is ""!  This is the key point, you can print(text_input)
> > image_inputs, video_inputs = process_vision_info(messages)
> > inputs = processor(
> > text=[text_input],
> > images=image_inputs,
> > videos=video_inputs,
> > padding=True,
> > return_tensors="pt")
> > inputs = inputs.to("cuda:0")
> > output_ids =model.generate(**inputs, max_new_tokens=256)
> > generated_ids_trimmed = [output_ids[len(input_ids):] for input_ids, output_ids in zip(inputs.input_ids, output_ids )]
> > response= processor.batch_decode(generated_ids_trimmed, skip_special_tokens=True, clean_up_tokenization_spaces=True)
> > it returns :
> > Traceback (most recent call last):
> > File "/data/lsd/work/LLM/JailBreakV_28K/attack_models/Qwen.py", line 64, in 
> > ret = model.inference("/data/lsd/work/LLM/JailBreakV_28K/JailBreakV_28k/query_related/SD_related_0.png", "hi!describe the picture")
> > File "/data/lsd/work/LLM/JailBreakV_28K/attack_models/Qwen.py", line 56, in inference
> > output_ids =self. model.generate(**inputs, max_new_tokens=256)
> > File "/data/lsd/anaconda3/envs/jbv/lib/python3.9/site-packages/torch/utils/_contextlib.py", line 115, in decorate_context
> > return func(*args, **kwargs)
> > File "/data/lsd/anaconda3/envs/jbv/lib/python3.9/site-packages/transformers/generation/utils.py", line 2465, in generate
> > result = self._sample(
> > File "/data/lsd/anaconda3/envs/jbv/lib/python3.9/site-packages/transformers/generation/utils.py", line 3424, in _sample
> > model_inputs = self.prepare_inputs_for_generation(input_ids, **model_kwargs)
> > File "/data/lsd/anaconda3/envs/jbv/lib/python3.9/site-packages/transformers/models/qwen2_vl/modeling_qwen2_vl.py", line 1764, in prepare_inputs_for_generation
> > model_inputs = super().prepare_inputs_for_generation(
> > File "/data/lsd/anaconda3/envs/jbv/lib/python3.9/site-packages/transformers/generation/utils.py", line 507, in prepare_inputs_for_generation
> > inputs_embeds, input_ids = self._cache_dependant_input_preparation(
> > File "/data/lsd/anaconda3/envs/jbv/lib/python3.9/site-packages/transformers/generation/utils.py", line 406, in _cache_dependant_input_preparation
> > or (cache_position[-1] >= input_ids.shape[1])  # Exception 3.(This may be varified due to your code.)
> > It may be due to the model in `huggingface` being something wrong. ~ If the `chat_template.json` in your model path is:
> > ```
> > { 
> >  "chat_template": "{% if messages is string %}{{ messages }}{% else %}{% for content in messages %}{% if content['type'] == 'image' or 'image' in content or 'image_url' in content %}<|vision_start|><|image_pad|><|vision_end|>{% elif content['type'] == 'video' or 'video' in content %}<|vision_start|><|video_pad|><|vision_end|>{% elif 'text' in content %}{{ content['text'] }}{% endif %}{% endfor %}{% endif %}" 
> >  } 
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > And you should use `chat_template.json` in `Qwen2.5` or other versions. I copy the belowing:
> > ```
> > {
> >     "chat_template": "{% set image_count = namespace(value=0) %}{% set video_count = namespace(value=0) %}{% for message in messages %}{% if loop.first and message['role'] != 'system' %}<|im_start|>system\nYou are a helpful assistant.<|im_end|>\n{% endif %}<|im_start|>{{ message['role'] }}\n{% if message['content'] is string %}{{ message['content'] }}<|im_end|>\n{% else %}{% for content in message['content'] %}{% if content['type'] == 'image' or 'image' in content or 'image_url' in content %}{% set image_count.value = image_count.value + 1 %}{% if add_vision_id %}Picture {{ image_count.value }}: {% endif %}<|vision_start|><|image_pad|><|vision_end|>{% elif content['type'] == 'video' or 'video' in content %}{% set video_count.value = video_count.value + 1 %}{% if add_vision_id %}Video {{ video_count.value }}: {% endif %}<|vision_start|><|video_pad|><|vision_end|>{% elif 'text' in content %}{{ content['text'] }}{% endif %}{% endfor %}<|im_end|>\n{% endif %}{% endfor %}{% if add_generation_prompt %}<|im_start|>assistant\n{% endif %}"
> > }
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > Then you should replace your `chat_template.json` with the bellow one. And this may help you.
> 
> 你这个和Issue的报错不一样吧，我在llava里也看到你了



> 😭 我解决了 为什么Qwen2-vl-7B出错了。 废话不多说，先看我的代码 Code run faster than my word:
> 
> model_name = '/path/to/Qwen2-VL-7B' 
> processor = AutoProcessor.from_pretrained(model_name,trust_remote_code=True)
> model = Qwen2VLForConditionalGeneration.from_pretrained(model_name, device_map="auto", trust_remote_code=True)
> 
> messages = [
>     {
>         "role": "user",
>         "content":[ 
>         {
>         "type":"text" ,"text":"TELL ME WHY!!!!"
>         }
>     ]
>     }
> ]
> 
> text_input = processor.apply_chat_template(messages, tokenize=False, add_generation_prompt=True)
> # About the text_input, it is ""!  This is the key point, you can print(text_input)
> image_inputs, video_inputs = process_vision_info(messages)
> inputs = processor(
>             text=[text_input],
>             images=image_inputs,
>             videos=video_inputs,
>             padding=True,
>             return_tensors="pt")
> inputs = inputs.to("cuda:0")
> output_ids =model.generate(**inputs, max_new_tokens=256)
> generated_ids_trimmed = [output_ids[len(input_ids):] for input_ids, output_ids in zip(inputs.input_ids, output_ids )]
> response= processor.batch_decode(generated_ids_trimmed, skip_special_tokens=True, clean_up_tokenization_spaces=True)
> it returns :
> 
> Traceback (most recent call last):
>   File "/data/lsd/work/LLM/JailBreakV_28K/attack_models/Qwen.py", line 64, in <module>
>     ret = model.inference("/data/lsd/work/LLM/JailBreakV_28K/JailBreakV_28k/query_related/SD_related_0.png", "hi!describe the picture")
>   File "/data/lsd/work/LLM/JailBreakV_28K/attack_models/Qwen.py", line 56, in inference
>     output_ids =self. model.generate(**inputs, max_new_tokens=256)
>   File "/data/lsd/anaconda3/envs/jbv/lib/python3.9/site-packages/torch/utils/_contextlib.py", line 115, in decorate_context
>     return func(*args, **kwargs)
>   File "/data/lsd/anaconda3/envs/jbv/lib/python3.9/site-packages/transformers/generation/utils.py", line 2465, in generate
>     result = self._sample(
>   File "/data/lsd/anaconda3/envs/jbv/lib/python3.9/site-packages/transformers/generation/utils.py", line 3424, in _sample
>     model_inputs = self.prepare_inputs_for_generation(input_ids, **model_kwargs)
>   File "/data/lsd/anaconda3/envs/jbv/lib/python3.9/site-packages/transformers/models/qwen2_vl/modeling_qwen2_vl.py", line 1764, in prepare_inputs_for_generation
>     model_inputs = super().prepare_inputs_for_generation(
>   File "/data/lsd/anaconda3/envs/jbv/lib/python3.9/site-packages/transformers/generation/utils.py", line 507, in prepare_inputs_for_generation
>     inputs_embeds, input_ids = self._cache_dependant_input_preparation(
>   File "/data/lsd/anaconda3/envs/jbv/lib/python3.9/site-packages/transformers/generation/utils.py", line 406, in _cache_dependant_input_preparation
>     or (cache_position[-1] >= input_ids.shape[1])  # Exception 3.(This may be varified due to your code.)
> It may be due to the model in `huggingface` being something wrong. ~ If the `chat_template.json` in your model path is:
> 
> ```
> { 
>  "chat_template": "{% if messages is string %}{{ messages }}{% else %}{% for content in messages %}{% if content['type'] == 'image' or 'image' in content or 'image_url' in content %}<|vision_start|><|image_pad|><|vision_end|>{% elif content['type'] == 'video' or 'video' in content %}<|vision_start|><|video_pad|><|vision_end|>{% elif 'text' in content %}{{ content['text'] }}{% endif %}{% endfor %}{% endif %}" 
>  } 
> ```
> 
> And you should use `chat_template.json` in `Qwen2.5` or other versions. I copy the belowing:
> 
> ```
> {
>     "chat_template": "{% set image_count = namespace(value=0) %}{% set video_count = namespace(value=0) %}{% for message in messages %}{% if loop.first and message['role'] != 'system' %}<|im_start|>system\nYou are a helpful assistant.<|im_end|>\n{% endif %}<|im_start|>{{ message['role'] }}\n{% if message['content'] is string %}{{ message['content'] }}<|im_end|>\n{% else %}{% for content in message['content'] %}{% if content['type'] == 'image' or 'image' in content or 'image_url' in content %}{% set image_count.value = image_count.value + 1 %}{% if add_vision_id %}Picture {{ image_count.value }}: {% endif %}<|vision_start|><|image_pad|><|vision_end|>{% elif content['type'] == 'video' or 'video' in content %}{% set video_count.value = video_count.value + 1 %}{% if add_vision_id %}Video {{ video_count.value }}: {% endif %}<|vision_start|><|video_pad|><|vision_end|>{% elif 'text' in content %}{{ content['text'] }}{% endif %}{% endfor %}<|im_end|>\n{% endif %}{% endfor %}{% if add_generation_prompt %}<|im_start|>assistant\n{% endif %}"
> }
> ```
> 
> Then you should replace your `chat_template.json` with the bellow one. And this may help you.

你这个不太一样 这个似乎只是因为Qwen raw model 和Instruct-version 在chat template 上的区别吧
